[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo  = 'ternjs/tern_for_vim'
on_ft = ['javascript']
hook_post_update = '''
let g:dein#plugin.build = 'npm install'
'''
# ====== Programming Languages =====
[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffeescript']
# [[plugins]]
# repo  = 'pangloss/vim-javascript'
# on_ft = ['javascript']
# [[plugins]]
# repo = 'vim-scripts/JavaScript-syntax'
# on_ft = ['javascript']
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']
# [[plugins]]
# repo = 'vim-scripts/jQuery'
# on_ft = ['javascript']
# [[plugins]]
# repo  = 'MaxMEllon/vim-jsx-pretty'
# repo  = 'mxw/vim-jsx'
# on_ft = ['javascript']

[[plugins]]
repo  = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo  = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

[[pugins]]
repo  = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo  = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']
# [[plugins]]
# repo  = 'cespare/vim-go'
# on_ft = ['go']
[[plugins]]
repo  = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo  = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
repo  = 'editorconfig/editorconfig-vim'
on_ft = ['editorconfig']

[[plugins]]
repo  = 'uarun/vim-protobuf'
on_ft = ['protobuf']

[[plugins]]
repo  = 'fatih/vim-nginx'

[[plugins]]
repo  = 'tfnico/vim-gradle'
on_ft = ['gradle']

[[plugins]]
repo  = 'kylef/apiblueprint.vim'
on_ft = ['apiblueprint']

[[plugins]]
repo  = 'yukpiz/vim-volt-syntax'
on_ft = ['volt']
