[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  syntax enable
  set background=dark
  let g:onedark_color_overrides = {
   \"black": {"gui": "#000000", "cterm": "16", "cterm16": "0" },
  \}
  let g:onedark_termcolors = 256

  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
  autocmd MyAutoCmd VimEnter * nested colorscheme onedark
'''

# [[plugins]]
# repo = 'morhetz/gruvbox'
# hook_add = '''
#   " soft/medium/hard
#   " color palette
#   " https://github.com/morhetz/gruvbox#palette
#   syntax enable
#   set background=dark
#   let g:gruvbox_bold=1
#   let g:gruvbox_italic=0
#   let g:gruvbox_transparent_bg=0
#   let g:gruvbox_underline=1
#   let g:gruvbox_undercurl=1
#   let g:gruvbox_termcolors=256
#   let g:gruvbox_contrast_dark="hard"
#   let g:gruvbox_contrast_light="hard"
#   let g:gruvbox_hls_cursor="orange"
#   let g:gruvbox_sign_column="bg1"
#   let g:gruvbox_color_column="bg1"
#   let g:gruvbox_vert_split="bg0"
#   let g:gruvbox_italicize_comments=1
#   let g:gruvbox_italicize_strings=0
#   let g:gruvbox_invert_selection=0
#   let g:gruvbox_invert_selection=0
#   let g:gruvbox_invert_indent_guides=0
#   let g:gruvbox_invert_tabline=0
#   let g:gruvbox_improved_strings=0
#   let g:gruvbox_improved_warnings=0
#   let g:gruvbox_guisp_fallback="bg"
#
#   " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
#   " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
#   autocmd MyAutoCmd VimEnter * nested colorscheme gruvbox
# '''
[[plugins]]
repo = 'preservim/nerdtree'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends =  ['vim-fugitive']
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=100
'''
[[plugins]]
repo = 'c9s/cascading.vim'
[[plugins]]
repo = 'preservim/nerdcommenter.git'
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'vim-scripts/camelcasemotion'
[[plugins]]
repo  = 'junegunn/fzf.vim'
on_cmd = [
    'Files',
    'ProjectFiles',
    'Buffers',
    'BLines',
    'History',
    'Tags',
    'BTags',
    'GFiles',
    'Ag',
]
[[plugins]]
repo = 'othree/eregex.vim'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_add = '''
  if executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'fholgado/minibufexpl.vim'
[[plugins]]
repo = 'preservim/tagbar'
[[plugins]]
repo = 'osyo-manga/shabadou.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-lsp-icons'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
# [[plugins]]
# repo = 'Shougo/defx.nvim'
# [[plugins]]
# repo = 'jeetsukumaran/vim-buffergator'
