[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'preservim/nerdtree'
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
		nnoremap [figitive] <Nop>
		nnoremap <Leader>g [figitive]
		nnoremap <silent> [figitive]s :<C-u>Gstatus<CR>
		nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
		nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
'''
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends =  ['vim-fugitive']
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'c9s/cascading.vim'
[[plugins]]
repo = 'preservim/nerdcommenter.git'
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'vim-scripts/camelcasemotion'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'yegappan/grep'
[[plugins]]
repo = 'othree/eregex.vim'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'vim-scripts/errormarker.vim'
[[plugins]]
repo = 'dense-analysis/ale'
[[plugins]]
repo = 'fholgado/minibufexpl.vim'
[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'yuroyoro/yuroyoro256.vim'
[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'xwsoul/vim-zephir'
[[plugins]]
repo = 'osyo-manga/shabadou.vim'
[[plugins]]
repo  = 'neoclide/coc.nvim'
rev   = 'release'
merge = 0
[[plugins]]
repo  = 'antoinemadec/coc-fzf'
[[plugins]]
repo  = 'josa42/coc-go'
[[plugins]]
repo  = 'junegunn/fzf.vim'
